# Generated by Django 4.2.16 on 2024-11-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
    ]
